### ISSUE TITLE
add settings to configure types of notifications shown in UI

### ISSUE THREAD

**Issue by triptu** [100mslive/100ms-web#420]
in large rooms, notifications on peer join, leave new message etc. can be bothering. It would be nice to have a configuration in the UI settings where one can select what types of notifications they want.

<img width="449" alt="Screenshot 2021-10-04 at 9 20 55 AM" src="https://user-images.githubusercontent.com/16299282/135790180-34482099-b0a7-439e-9eec-8afa3c1982ce.png">
<img width="449" alt="Screenshot 2021-10-04 at 9 22 21 AM" src="https://user-images.githubusercontent.com/16299282/135790269-fd8e8943-d745-4415-8986-db138af58fd9.png">

Task - 
- [ ]  Rename Layout Settings above to UI Settings 
- [ ]  Rename title from Participant in View to UI settings and make participant text to left of the slider.
- [ ]  Add new section for Notifications with checkboxes for Peer Join/Peer Leave/New Message/Errors
- [ ]  Make sure only the selected notifications are sent from here - https://github.com/100mslive/100ms-web/blob/main/src/views/components/notifications/Notifications.jsx

**Comment by mani-rsg** [comment]
Hi @triptu , I would like to work on this can you please assign me this?

**Comment by triptu** [comment]
sure, assigned.

**Comment by mani-rsg** [comment]
Hi @triptu, 

I was able to complete the first task when I was trying the second task, I identified that the change should be done in the "ParticipantsInView" component however, I noticed that "ParticipantsInView" component is imported from the npm package "@100mslive/hms-video-react", I reckon the major part of the change should be done in the npm package. How can we proceed? 

If you assign me this issue in that repo I could make the changes in that as well

**Comment by triptu** [comment]
The component is part of this package - https://github.com/100mslive/hms-video-react (which also has hacktoberfest label btw), you can create a PR there for any changes related to this and bump the version in package.json, on merge the version will get published automatically. To test locally you can use `yarn link` to connect both the repos.

1. In hms-video-react
```
yarn link
```

2. In web(this repo)
```
yarn link @100mslive/hms-video-react
cd node-modules/react
yarn link
```

3. In hms-video-react
```
yarn link react
```

Then run yarn start in both repos and you'll have them linked up, so any change you do in react components will show up locally on watch. Feel free to let me know of any other issues.
