### ISSUE TITLE
make chat component work properly in mobile web

### ISSUE THREAD

**Issue by triptu** [100mslive/100ms-web#421]
we've disabled the chat button in mobile browsers currently because it breaks the UI and is not really usable on phone due to the width being small. We can increase the width on mweb conditionally, so user can participate in chat from phone, ipads etc. too.

<img width="412" alt="Screenshot 2021-10-04 at 9 40 50 AM" src="https://user-images.githubusercontent.com/16299282/135791531-c9777785-fb51-4fdc-83c1-35d2f0b0c745.png">

We can make it an overlay on top of other things so it can have proper width in mobile as well.

**Comment by kushalShukla-web** [comment]
may i ? pls

**Comment by triptu** [comment]
sure, go ahead.

**Comment by kushalShukla-web** [comment]
so i have to create whole chat component?

**Comment by triptu** [comment]
No just make the existing one work properly on phone. 
Can you create an account on dashboard.100ms.live? You'll get a room url you can join and try check it out on phone and pc.

**Comment by ranjithkumark8** [comment]
Hi @triptu, Can I work on this issue?

**Comment by triptu** [comment]
sure, assigned to you.

**Comment by ranjithkumark8** [comment]
Hi @triptu, I noticed that "ChatBox" component is imported from the npm package "@100mslive/hms-video-react", I think major part of the change should be done in the npm package. How can I proceed?

**Comment by raviteja83** [comment]
https://github.com/100mslive/hms-video-react you can contribute here.

**Comment by ranjithkumark8** [comment]
Ok thanks for the update @raviteja83

**Comment by ranjithkumark8** [comment]
@triptu @raviteja83 
After updating .env file with variables in example.env. I'm getting following error(see below screenshot). I tried to resolve it but I couldn't able to resolve it. Can you please help me with this?
![image](https://user-images.githubusercontent.com/57569434/136495329-5f385a87-9727-43ed-92e4-ed468cbd9492.png)
![image](https://user-images.githubusercontent.com/57569434/136495562-db3938f0-680e-4e9f-8b60-b4eca6cd7cd6.png)

**Comment by triptu** [comment]
Have you created an account on dashboard.100ms.live to give the token endpoint in .env?

**Comment by mani-rsg** [comment]
@ranjithkumark8  Fill the REACT_APP_POLICY_CONFIG in the env with '{}', then it should work. Check the README.md (now updated)

**Comment by ranjithkumark8** [comment]
@mani-rsg Thanks, issue got resolved.  Working on it.

**Comment by ranjithkumark8** [comment]
Hi @triptu @mani-rsg @raviteja83,

Can someone help me with this issue? I have linked hms-web with hms-video-react after that I'm getting below errors.

We don't have ParticipantsInView component in hms-video-react but we are importing it in MoreSettings in hms-web.

after commenting ParticipantsInView in MoreSettings, I'm getting Invalid hook error in HMSRoomProvider, Even though we are using it in functional component. 

![image](https://user-images.githubusercontent.com/57569434/136835177-77e8862a-260c-4f90-a4ea-9b70428b4766.png)
![image](https://user-images.githubusercontent.com/57569434/136835256-e9d5afb9-eb10-41ab-a0c9-2eb011c581cc.png)

**Comment by mani-rsg** [comment]
Hi @ranjithkumark8, I just looked at your forked repo of 100ms-web and it is behind the upstream and that's why there is a version mismatch, please pull and merge upstream, and then link hms-web with hms-video-react and it should work.
![image](https://user-images.githubusercontent.com/72298612/136890748-ad41b6c8-a935-445d-b9e3-1474a691de7a.png)

You can use the yarn link to connect both the repos.

In hms-video-react

> yarn link

In web(this repo)

> yarn link @100mslive/hms-video-react
> cd node-modules/react
> yarn link

In hms-video-react

> yarn link react

Then run yarn start in both repos and you'll have them linked up, so any change you do in react components will show up locally on watch. (these steps to link repos are mentioned by @triptu  in another issue that worked for me)

**Comment by ranjithkumark8** [comment]
Thanks @mani-rsg I will check it out
