### ISSUE TITLE
add go to docs option in menu

### ISSUE THREAD

**Issue by triptu** [100mslive/100ms-web#422]
add go to docs option in center menu which takes to docs.100ms.live

**Comment by harshmathurx** [comment]
hey @triptu can you provide a little more context?

**Comment by triptu** [comment]
Sure, in the center menu in the below image, it would be nice to have one more option call `Open Docs` which opens the documentation page - https://docs.100ms.live/javascript/v2/foundation/basics . 

<img width="498" alt="Screenshot 2021-10-04 at 12 47 03 PM" src="https://user-images.githubusercontent.com/16299282/135809118-3971d30c-5c2b-4992-ab87-d8a0cb436c24.png">

The image to be used will be this svg which can be added to our react components repo(also labelled for hactoberfest) similar to this PR - https://github.com/100mslive/hms-video-react/pull/389/files 
```
<svg width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M8 16.4756C12.2554 16.4756 15.7563 12.9746 15.7563 8.71924C15.7563 4.45654 12.2554 0.955566 7.99268 0.955566C3.72998 0.955566 0.236328 4.45654 0.236328 8.71924C0.236328 12.9746 3.7373 16.4756 8 16.4756ZM7.99268 6.36816C7.36279 6.36816 6.83545 5.84082 6.83545 5.21094C6.83545 4.55908 7.36279 4.04639 7.99268 4.04639C8.62256 4.04639 9.14258 4.55908 9.14258 5.21094C9.14258 5.84082 8.62256 6.36816 7.99268 6.36816ZM6.60107 12.8428C6.19092 12.8428 5.86865 12.5571 5.86865 12.125C5.86865 11.7368 6.19092 11.4219 6.60107 11.4219H7.44336V8.81445H6.74756C6.33008 8.81445 6.01514 8.52148 6.01514 8.104C6.01514 7.7085 6.33008 7.40088 6.74756 7.40088H8.24902C8.77637 7.40088 9.04736 7.75977 9.04736 8.31641V11.4219H9.71387C10.124 11.4219 10.4463 11.7368 10.4463 12.125C10.4463 12.5571 10.124 12.8428 9.71387 12.8428H6.60107Z" fill="white"/>
</svg>
```

**Comment by harshmathurx** [comment]
I'll try working on this 
Thanks

**Comment by triptu** [comment]
@harshmathurx are you working on this?

**Comment by harshmathurx** [comment]
I tried running it in my local machine and getting the keys from 100ms, that worked but as soon as I try to get in to a meeting on localhost, it throws an error

**Comment by Deep-Codes** [comment]
> I tried running it in my local machine and getting the keys from 100ms, that worked but as soon as I try to get in to a meeting on localhost, it throws an error

Can you share what's the error?

**Comment by harshmathurx** [comment]
Solved the 404 error,
how do I add the SVG Icon? Do I have to make a PR to `hms-video-react`?
currently, it looks like this 
![image](https://user-images.githubusercontent.com/58532371/136905355-ed96fd8f-d9ff-4d95-8170-745f0d081710.png)

**Comment by triptu** [comment]
@harshmathurx  yes.

**Comment by harshmathurx** [comment]
@triptu aight I'll make that PR

**Comment by manavdesai27** [comment]
Is there any work left to do on this issue?
