### ISSUE TITLE
Issue while local setup

### ISSUE THREAD

**Issue by mani-rsg** [100mslive/100ms-web#424]
**Describe the bug**
While I follow the steps mentioned in the Readme.md to set up the application locally for enhancement, found following issues:

- In the actual application the code `const envPolicyConfig = JSON.parse(process.env.REACT_APP_POLICY_CONFIG || "{}");
`. was present as `const envPolicyConfig = JSON.parse(process.env.REACT_APP_POLICY_CONFIG || false);
` which caused an error while parsing, so I was able to see only a blank screen.

- A closing curly brace was missing in the example of REACT_APP_POLICY_CONFIG `REACT_APP_POLICY_CONFIG = "{"trainer":{"center": ["student"],"sidepane":["trainer"]}"`

**To Reproduce**
1. Just follow the steps one by one and try to run the app locally and you'll face this issue.

**Comment by triptu** [comment]
can you please send a PR with both of these fixed as well? thanks.

**Comment by mani-rsg** [comment]
Sure

**Comment by mani-rsg** [comment]
Updated the Readme.md and Rasied PR
