### ISSUE TITLE
Take User feedback after leave page

### ISSUE THREAD

**Issue by triptu** [100mslive/100ms-web#425]
make a UI component to take user feedback after leave page. For now, this will only be printing the feedback to console. Design mockup for the component - 

![image](https://user-images.githubusercontent.com/16299282/135843449-3d7ea7e0-6875-4e48-a8c2-066064b2ec42.png)

In above leave page is already there, the send feedback button is required in center bottom, which when clicked opens the below modal.

![image](https://user-images.githubusercontent.com/16299282/135886715-1ee8278f-da29-45ba-8182-87928400ef3f.png)
![image](https://user-images.githubusercontent.com/16299282/135886773-ca793738-74c2-4f24-9655-0e7f79a6df5b.png)
![image](https://user-images.githubusercontent.com/16299282/135886827-a86efc2d-c36b-499c-ba9c-b17480f65986.png)

**Comment by Chris-Blesson** [comment]
Hi @triptu  can you assign this to me ?

**Comment by Chris-Blesson** [comment]
Hi @triptu I was checking the code for this issue, looks like the component "PostLeaveDisplay" is imported from "@100mslive/hms-video-react". So should I make changes on both ?

**Comment by Chris-Blesson** [comment]
Hi @Deep-Codes I believe I have to build custom components for this. I checked the existing components "Message Modal" but It is slightly different from the mentioned UI. Can you confirm If I can go ahead with this ?

**Comment by triptu** [comment]
Yes you can go ahead with that. Slight changes are fine.

**Comment by triptu** [comment]
Icons, can be put in public folder - 
![image](https://user-images.githubusercontent.com/16299282/136565021-afa7a560-de6e-40cb-9e74-00a42f3d043a.png)
![image](https://user-images.githubusercontent.com/16299282/136565195-2a04c01f-ca3c-477e-a949-53d6719a294d.png)

**Comment by Chris-Blesson** [comment]
Thanks for the help @triptu
