### ISSUE TITLE
save UI settings in local storage for next join

### ISSUE THREAD

**Issue by triptu** [100mslive/100ms-web#443]
save UI settings in local storage and remember them for next join.

<img width="470" alt="Screenshot 2021-10-11 at 4 57 39 PM" src="https://user-images.githubusercontent.com/16299282/136782767-fe1a96df-1bae-4828-862c-c4003b5b3046.png">

**Comment by mani-rsg** [comment]
Hi @triptu, would like to work on this can you please assign me this issue?

**Comment by LuizHAP** [comment]
Hi @triptu can u please assign to me?

**Comment by triptu** [comment]
Assigned to @mani-rsg 
@LuizHAP Let me figure out something similar, I'll add in a while.

**Comment by triptu** [comment]
@LuizHAP please check - https://github.com/100mslive/100ms-web/issues/445
