### ISSUE TITLE
make leave easier to click than end room

### ISSUE THREAD

**Issue by triptu** [100mslive/100ms-web#445]
if you have the permission to end room, this is how the UI currently looks when clicked on leave room
<img width="307" alt="Screenshot 2021-10-11 at 6 45 52 PM" src="https://user-images.githubusercontent.com/16299282/136796571-0fc40edb-6386-416d-a353-d30f78171f7b.png">

It's much easier to click on end room by mistake. Two things are required -
* Switch the order of end room and leave room, so leave is down and end is up.
* Highlight the leave button with red color instead of the endroom

**Comment by triptu** [comment]
@LuizHAP can you pick this one?

**Comment by Bipul-Harsh** [comment]
> if you have the permission to end room, this is how the UI currently looks when clicked on leave room <img alt="Screenshot 2021-10-11 at 6 45 52 PM" width="307" src="https://user-images.githubusercontent.com/16299282/136796571-0fc40edb-6386-416d-a353-d30f78171f7b.png">
> 
> It's much easier to click on end room by mistake. Two things are required -
> 
> * Switch the order of end room and leave room, so leave is down and end is up.
> * Highlight the leave button with red color instead of the endroom

here you mean end room is down and leave room is up right?

**Comment by Bipul-Harsh** [comment]
![image](https://user-images.githubusercontent.com/52464028/136822871-bfd66e61-a44a-4756-bbe3-f41635dd36e9.png)
Can you tell me which one is the correct output you mean

**Comment by Bipul-Harsh** [comment]
BTW I am ready to work on it so you can assign it to me

**Comment by manavdesai27** [comment]
@triptu I have previously worked on such issues. Can I work on this one?

**Comment by manavdesai27** [comment]
@triptu 100ms developer dashboard is down right now?

**Comment by manavdesai27** [comment]
I have made the changes but the token might have expired.

**Comment by manavdesai27** [comment]
@triptu please review this PR

**Comment by triptu** [comment]
closed in https://github.com/100mslive/100ms-web/pull/447
