### ISSUE TITLE
add full screen option to screenshare

### ISSUE THREAD

**Issue by triptu** [100mslive/100ms-web#450]
it should be possible to fullscreen a screenshare

We have it for video playlist already and the button looks like this -

<img width="1141" alt="Screenshot 2021-10-12 at 5 32 54 PM" src="https://user-images.githubusercontent.com/16299282/136953983-f9de0635-b8c9-4431-9314-9ef64c82dada.png">

The way to do this would be changing the VideoTile here - https://github.com/100mslive/hms-video-react/blob/main/src/components/VideoTile/VideoTile.tsx to add a small fullscreen icon which acts similar to video playlist screenshare button. Here is the function which is used by the video playlist component which can be traced back to learn more - https://github.com/100mslive/hms-video-react/blob/c90fb6a62e7532a6e7dabe006b015c8e056c0f7e/src/utils/index.ts#L643

**Comment by manavdesai27** [comment]
@triptu Can I work on this?

**Comment by triptu** [comment]
sure. Assigned to you.

**Comment by manavdesai27** [comment]
@triptu Can you explain the issue again? I have one doubt. Say, the teacher is sharing the screen and the student is watching it. Should the full screen button come to student or teacher? The teacher shouldn't get it right, because he/she would already be sharing the screen and would by default be in full screen mode.

**Comment by manavdesai27** [comment]
Also can you help me reproduce the playlist fullscreen feature?

**Comment by triptu** [comment]
yes the full screen will be there for all screenshare video tiles. Teacher might be sharing only a chrome tab or one window. If the teacher is sharing the whole screen, they won't see the screenshare tile but a generic you're sharing your screen. You can try these out on the room link to check the behaviour.

The option to play a video is on lower left side - 
<img width="320" alt="Screenshot 2021-10-12 at 10 16 41 PM" src="https://user-images.githubusercontent.com/16299282/136997159-19b4864f-6967-4679-8810-53671467aec3.png">
You can join the same room from other tab to see how it looks on the receiving side(and the full screen button).
To try locally set the `REACT_APP_VIDEO_PLAYLIST` env variable with jsonified string of sth like - 

<details>
<summary>Details</summary>

```
[
  {
    "name": "100ms-360P",
    "id": "video1",
    "metadata": {
      "description": "100ms"
    },
    "url": "https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/100ms-360p.mp4",
    "type": "video"
  },
  {
    "name": "100ms-720P",
    "id": "video2",
    "metadata": {
      "description": "100ms"
    },
    "url": "https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/100ms-720p.mp4",
    "type": "video"
  },
  {
    "name": "Big Buck Bunny",
    "id": "video3",
    "metadata": {
      "description": "Bunny"
    },
    "url": "https://d2qi07yyjujoxr.cloudfront.net/webapp/playlist/video2.mp4",
    "type": "video"
  }
]
```

</details>

**Comment by manavdesai27** [comment]
Is the 100ms server down? It isn't loading any data in my developer dashboard.

**Comment by triptu** [comment]
Can you send the link you're trying?

**Comment by manavdesai27** [comment]
[Dashboard](https://dashboard.100ms.live/dashboard)

**Comment by triptu** [comment]
It seems to be working fine, can you share a screenshot?

**Comment by manavdesai27** [comment]
Yeah sure
![Screenshot from 2021-10-13 11-17-06](https://user-images.githubusercontent.com/74018438/137074392-30b98c2c-bceb-49c8-a5dd-afd4b44cb9a3.png)
![Screenshot from 2021-10-13 11-17-00](https://user-images.githubusercontent.com/74018438/137074402-07088c0b-be19-4db7-a8af-021c02d64841.png)

**Comment by manavdesai27** [comment]
Okay. It seems it isn't working in my brave browser. But its working fine in Chrome.

**Comment by manavdesai27** [comment]
@triptu We have to make changes here only right? https://github.com/100mslive/hms-video-react/blob/main/src/components/VideoTile/VideoTile.tsx

**Comment by triptu** [comment]
Yes, it takes in a boolean showScreenshare which can be used to decide if the full-screen option needs to be shown.

**Comment by manavdesai27** [comment]
Can you copy paste your complete REACT_APP_VIDEO_PLAYLIST line of env?

**Comment by manavdesai27** [comment]
@triptu I am abandoning this issue for now.

**Comment by mani-rsg** [comment]
Hi @triptu , Would like to work on this can you assign me ?

**Comment by triptu** [comment]
sure, assigned.

**Comment by mani-rsg** [comment]
Hi @triptu, Looks like 100ms-web currently doesn't use the latest version of the hms-video-react package so I haven't updated the hms-video-react version in the package.json. Let me know if I have to update the version in 100ms-web and raise PR for the same.
