### ISSUE TITLE
create multi select component

### ISSUE THREAD

**Issue by raviteja83** [100mslive/100ms-web#467]
Replace the select for roles with multi select where multiple roles can be selected.

![image](https://user-images.githubusercontent.com/6763261/137881057-7f8290a8-d37d-48a2-a2b6-60cea185fbf3.png)

click on mute all from above menu to open the following modal

![image](https://user-images.githubusercontent.com/6763261/137880581-4cd0895b-05ea-4141-a13f-aa29b34e61b1.png)

**Comment by pratik9333** [comment]
Can I do it? @raviteja83

**Comment by triptu** [comment]
sure, assigning to you @pratik9333 , note that it will also require changes in this repo - https://github.com/100mslive/hms-video-react

**Comment by pratik9333** [comment]
![image](https://user-images.githubusercontent.com/69317773/138551458-87419689-b166-4ceb-8b64-7edd1bb761ba.png)

@triptu hello, I'am facing this issue while running app in localhost!

**Comment by pratik9333** [comment]
I have updated TOKEN_GENERATION_ENDPOINT but don't know to update REACT_APP_POLICY_CONFIG can you please help me on this ? @triptu

**Comment by triptu** [comment]
Can you try setting `REACT_APP_POLICY_CONFIG={}` in .env?

**Comment by pratik9333** [comment]
Yeah it worked, but when I'm going to this URL asking name but button is disabled named join. http://localhost:3000/preview/6173d788af3188df33e6316a/teacher @triptu

**Comment by triptu** [comment]
Is it disabled even after typing in the name? Have you give camera and mic permissions?

**Comment by pratik9333** [comment]
Yeah its disabled after typing name, although it didn't asked for camera and mic permissions

**Comment by triptu** [comment]
OS and browser? Did it never ask or was deny done the first time? Can you try any other browser as well.
If permission was denied it'll need to be manually allowed 
 https://support.google.com/chrome/answer/2693767?hl=en&co=GENIE.Platform%3DDesktop&oco=0

**Comment by pratik9333** [comment]
Using windows 11 and chrome browser. It never asked for it actually

**Comment by pratik9333** [comment]
Used different browser, didn't worked

**Comment by pratik9333** [comment]
@triptu

**Comment by triptu** [comment]
where did you get the room id and role from? The above room doesn't have any role named teacher. 
It has host though, this might work - http://localhost:3000/preview/6173d788af3188df33e6316a/host if the token endpoint is properly configured.

**Comment by pratik9333** [comment]
Room id I got from 100ms website only as mention in readme that we have to generate endpoint token and all for configuration.

**Comment by pratik9333** [comment]
It worked! Thank you :D

**Comment by pratik9333** [comment]
![image](https://user-images.githubusercontent.com/69317773/138553674-23f9a405-b1d1-4240-ba9e-3553805e7e6b.png)


One doubt, here in roles row, I have to change this dropdown to multiselect where he can selecr host and guest too at same time correct?

**Comment by pratik9333** [comment]
@triptu

**Comment by triptu** [comment]
yes that is correct

**Comment by mwangiwambui** [comment]
Hi @triptu , I am getting the below error when I try to join a room
![Screenshot from 2022-05-06 18-42-44](https://user-images.githubusercontent.com/26668383/167166808-406e3ff8-e021-43b8-941d-bec6f53686dd.png)

**Comment by triptu** [comment]
@mwangiwambui can you create a new github issue with more details around steps you did and saw the issue?
