### ISSUE TITLE
Merge Music, Playlist Music and recording into one component

### ISSUE THREAD

**Issue by raviteja83** [100mslive/100ms-web#483]
`headerView` has the above components. Right now, all three are independent. Take up lot of space.

When recording, Audio only screenshare, Audioplaylist are on, they overlap with active speaker. They also don't look good in mobile. They need to be combined into one dropdown menu like UI. 

Note: share some screenshots of  the ideas before getting into implementation.

**Comment by akshitarora921** [comment]
@raviteja83 Can I take this?

**Comment by raviteja83** [comment]
sure assigning to you.

**Comment by raviteja83** [comment]
When three ore more are active, you can use the following. You can use this for mobile event with one.
![image](https://user-images.githubusercontent.com/6763261/139650536-c771d531-4364-4595-94aa-faed0d9d1808.png)
