### ISSUE TITLE
Error while Joining

### ISSUE THREAD

**Issue by lazzyms** [100mslive/100ms-web#495]
**Describe the bug**
On the `join` method the SDK loggin this error:

```
{
code: 401
action: "INIT"
name: "ServerErrors"
message: "[INIT]: Server error"
description: "json: cannot unmarshal number into Go struct field Claims.user_id of type string"
isTerminal: false
timestamp: Fri Oct 29 2021 18:26:03 GMT+0530 (India Standard Time)
}
```
The official example code sandbox is also facing this issue: https://codesandbox.io/s/hms-js-quickstart-5rmes?from-embed

**Comment by triptu** [comment]
Hi! Thanks for reporting. I hope this is resolved now as discussed over discord.
For future reference, user_id in the formed token should be string instead of number.
