### ISSUE TITLE
ServerErrors: urls missing, when trying to Stream Live on Youtube

### ISSUE THREAD

**Issue by obisiket1** [100mslive/100ms-web#504]
ServerErrors: urls missing
    Wrapper vendors~main.chunk.js:15262
    HMSException HMSException.ts:16
    ServerErrors ErrorFactory.ts:210
    _callee$ index.ts:81
    Babel 10
    _callee12$ index.ts:254
    Babel 8
    _callee26$ index.ts:462
    Babel 8
    _callee19$ index.ts:646
    Babel 8
    _callee26$ HMSSDKActions.ts:445
    Babel 8
    stream Room.js:21
    React 14
    unstable_runWithPriority scheduler.development.js:468
    React 15
    js index.js:8
    js main.chunk.js:1495
    Webpack 7
index.js:1

Here is how my params is :

```js

await hmsActions.startRTMPOrRecording({
    meetingUrl: "https://t***.app.100ms.live/meeting/***/host",
    rtmpUrls: [
              "rtmp://a.rtmp.youtube.com/live2/******",
              "rtmp://b.rtmp.youtube.com/live2/******?backup=1"
            ],
    record: false
  })

```

**Comment by triptu** [comment]
@obisiket1 Hi! there is a typo in the params names -
```
interface RTMPRecordingConfig {
  meetingURL: string;
  rtmpURLs?: Array<string>;
  record: boolean;
}
```

**Comment by triptu** [comment]
@obisiket1 did this work?
