### ISSUE TITLE
SDK Cannot find Room Even when it exists

### ISSUE THREAD

**Issue by Codingmasters-YT** [100mslive/100ms-web#607]
**Describe the bug**
So i cloned this template, populated the example.env with my data, installed the dependencies via yarn and then started it. I saw the 404 page, as expected. SO i knew the server was up. Next I tried the localhost:3000/meeting/<room_id>/<role> URL, which should work, since the room exists and the role exists in the room. The token endpoint and room id are fine, i cross-checked them with the data in 100ms. But instead of a preview screen, i get the error message "ROOM DOES NOT EXIST"

**To Reproduce**
1. Clone this repo
2. Get your token endpoint from the 100ms developer page
3. Put it in the example.env where it asks you to
4. Install yarn dependencies, then start with ```yarn start```. go to localhost:3000/<room_id>/<role>, and then see the error

**Expected behavior**
I expected it to show me the preview screen, ask for device permissions and then let me join the room.

**Screenshots**
https://imgur.com/8K8WP9K.png

**Desktop (please complete the following information):**
 - OS: Kali Linux 5.16.0-kali7-amd64
 - Browser Firefox-esr
 - Version 91.8.0esr

**Comment by raviteja83** [comment]
The url has to be roomId/role. Can you try that. Also check the response of the init api call if you encounter the same issue again.

**Comment by triptu** [comment]
closing this due to no response, let us know if you're still facing this.
