### ISSUE TITLE
Mac touchpad swipe gesture handling disconnects users with slow connections

### ISSUE THREAD

**Issue by Braveado** [100mslive/100ms-web#629]
https://github.com/100mslive/100ms-web/blob/a86135a91dae40e7bdef7177e232cd9d68630878/src/components/conference.jsx#L54-L61

When joining a room, the referenced effect hook can disconnect users with a slow connection before they finish the room enter process.
This leaves the users with the FullPageProgress component inside the conference view infinitely showing its loader due to the following lines:
https://github.com/100mslive/100ms-web/blob/a86135a91dae40e7bdef7177e232cd9d68630878/src/components/conference.jsx#L63-L65

To reproduce:

1.  Set a low connection speed on the browser dev tools network tab.
2.  Refresh the page
3. Click join as soon as possible
![image](https://user-images.githubusercontent.com/44967097/196310737-9bf51917-d6c3-4ca7-b522-db0388f5ed20.png)

**Comment by raviteja83** [comment]
@Braveado possible to check this again?

**Comment by raviteja83** [comment]
closing now as the relevant code mentioned above is removed.
