### ISSUE TITLE
Closing a dialog on conference view prevents the use of other buttons

### ISSUE THREAD

**Issue by Braveado** [100mslive/100ms-web#631]
1. Go to the conference view
2. Open a dialog (end room confirmation, change name, settings)
3. Close the dialog

After closing a dialog the user should be able to continue to click buttons.

https://user-images.githubusercontent.com/44967097/199594725-1eeae32e-cc7b-4ea8-a78e-4b93e65e2c82.mov

Desktop:
 - OS: Windows & Mac
 - Browser: Mozilla & Chrome

**Comment by raviteja83** [comment]
fix merged to main
