### ISSUE TITLE
actions.changeRole causes dropped audio track on role change

### ISSUE THREAD

**Issue by tylerzey** [100mslive/100ms-web#633]
**Describe the bug**
I have 3 roles for my 100ms meeting (admin, guest, and waiting room).

For public meetings, the admin has an useEffect hook that monitors HMSNotificationTypes.PEER_JOINED in the waiting room. It automatically calls actions.changeRole upon getting the notifications.

Periodically (3/10 times) waiting room users upgraded to guest users will have their audio track not changeRoles with them.

They will still appear to have an audio track on their side, but on the admin side, it will look like they are muted and have no audio track.

**To Reproduce**
1. Go create 3 roles
2. For the admin role, have a useEffect that immediately calls actions.changeRole
3. See that the audio track on the guests role does not transfer roles

**Expected behavior**
The audio works as expected.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version latest.

**Comment by tylerzey** [comment]
Pulled this conversation into Discord: https://discord.com/channels/843749923060711464/843752786196693012/1039907872521343028

**Comment by raviteja83** [comment]
Resolved with https://github.com/100mslive/100ms-web/commit/df9f834d2e64bbac27532f1c89a5e17f7578c24a

https://www.100ms.live/docs/javascript/v2/changelog/release-notes#2022-12-19
