### ISSUE TITLE
hmsActions.changeName throws an error message if called with the current name of the peer

### ISSUE THREAD

**Issue by tylerzey** [100mslive/100ms-web#635]
**Describe the bug**
If you call hmsActions.changeName with the same name that the peer already has, the SDK errors.

**To Reproduce**
Video demo: https://www.loom.com/share/12d905e00cf24f3cafb066c4e83968a8

**Expected behavior**
The sdk should noop under the hood and not error. Or, throw a more helpful/clear, error message.

**Comment by raviteja83** [comment]
https://www.100ms.live/docs/javascript/v2/changelog/release-notes#2022-11-10

**Comment by tylerzey** [comment]
thanks!
