### ISSUE TITLE
Token returns null

### ISSUE THREAD

**Issue by amberx1** [100mslive/100ms-web#643]
I am a beginner-level programmer. I am trying to implement an audio conference feature in my app (written in Flutter). For some reason, the token request always returns null. I don't know what I'm doing wrong. Kindly go through the screenshots and help me find what I am doing wrongly. Thanks. 
![Screenshot (52)](https://user-images.githubusercontent.com/118815940/211158745-e32b7c52-9853-43da-a7c0-66da8b878c1a.png)
![Screenshot (53)](https://user-images.githubusercontent.com/118815940/211158750-fbb151e6-30be-4970-b83f-cdcf521b0656.png)

**Comment by ygit** [comment]
@amberx1 You are not passing the `role` param in the post request at line number: 59.

Refer the guide here: https://www.100ms.live/docs/flutter/v2/guides/token-endpoint
