### ISSUE TITLE
Not able to Join Calls

### ISSUE THREAD

**Issue by nikhilkumar828** [100mslive/100ms-web#658]
**Describe the bug**
Not able to join a scheduled call

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Call'
3. Click on 'Join Call'

**Expected behavior**
Should be able to join call

**Screenshots**
<img width="1792" alt="Screenshot 2023-04-08 at 10 25 38 AM" src="https://user-images.githubusercontent.com/19774379/230706399-9049e1e1-ce75-488e-9835-ad28a7f9081b.png">

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
High Priority - Giving a bad experience to Mentors, Might effect my profile

**Comment by raviteja83** [comment]
@nikhilkumar828 is the issue resolved? can you share console errors as well?
