### ISSUE TITLE
Not able to join calls

### ISSUE THREAD

**Issue by ashwingoyal154** [100mslive/100ms-web#660]
**Describe the bug**
Not able to join the call. It says: An error occurred while fetching the app token. Please look into logs for more details. If you think this is a mistake on our side, please create [an issue](https://github.com/100mslive/100ms-web/issues) or reach out over [Discord](https://discord.com/invite/kGdmszyzq2).

**To Reproduce**

**Expected behavior**
I was expecting to be able to join the call

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/44112341/233776010-4054f0fd-1d8e-4cc2-a052-4a68b702c214.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]

**Comment by raviteja83** [comment]
can you post a screenshot of network tab and console as well.
