### ISSUE TITLE
Please don't use GitHub stars to target spam

### ISSUE THREAD

**Issue by brettinternet** [100mslive/100ms-web#675]
I received this email addressed to "Brett jitsi/docker-jitsi-meet`:

> Reaching out to see if 100ms can help with in-app video conferencing/streaming,
> 
> 100ms is a SaaS platform that allows devs to add video conferencing & streaming to your Web, Android and iOS apps. We are used by Circle, Byjus, Kutumb, Circle and dozens of enterprises because:
> 
> 1. Native SDK -- Easy to use conferencing, recording, streaming, chat, interactivity in a single SDK
> 2. Works everywhere - Built by ex-Disney team to ensure it works seamlessly for across conditions 
> 3. Quick integration - Go live within days using pre-built apps, roles and components 
> 4. No maintenance - Our team is in charge of scaling, security, upgrades and reliability
> 
> If you see it relevant, can we schedule a quick 20 mins intro meeting?
> 
> Thanks in advance, 
> Jay Kanakiya,
> Account Executive, [100ms](https://100ms.live/)

Please don't use GitHub stars from Jitsi repositories to target spam.

https://github.com/jitsi/docker-jitsi-meet/issues/1589

**Comment by saghul** [comment]
This is pretty lame folks.

**Comment by aniketbehera** [comment]
Apologies @saghul @brettinternet we went overboard here, have stopped.
