### ISSUE TITLE
Sound Problem

### ISSUE THREAD

**Issue by rohanasylum** [100mslive/100ms-web#677]
**Describe the bug**
I made a video call app in react and when someone joining the call from ios device.first time voice not coming if ios user connect headshet and disconnect it then sound coming in the speaker..
**To Reproduce**

**Expected behavior**
i want if user join the meeting sound should come to speaker at first

 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone5s]

**Comment by raviteja83** [comment]
https://www.100ms.live/docs/javascript/v2/how-to-guides/debugging/error-handling#handling-autoplay-error
You should handle this.
